"""empty message

Revision ID: 582315d9543d_
Revises: 
Create Date: 2018-11-13 21:32:26.287985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582315d9543d_'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    subjects = op.create_table('subjects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('prerequisite', sa.Integer(), nullable=False),
        sa.Column('minimum_approved', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    types = op.create_table('types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    users = op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=150), nullable=False),
        sa.Column('email', sa.String(length=250), nullable=False),
        sa.Column('password', sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    nodes = op.create_table('nodes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=True),
        sa.Column('date_modified', sa.DateTime(), nullable=True),
        sa.Column('answer_parent', sa.String(length=250), nullable=False),
        sa.Column('parent_node', sa.Integer(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('type_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    user_subjects_rel = op.create_table('user_subjects_approved',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )

    # Seeding database
    op.bulk_insert(subjects, [
        {'name': 'Variables', 'minimum_approved': 10, 'prerequisite': 0},
        {'name': 'Estructuras de Control', 'minimum_approved': 20, 'prerequisite': 1},
        {'name': 'Bucles', 'minimum_approved': 35, 'prerequisite': 2},
        {'name': 'Arreglos', 'minimum_approved': 50, 'prerequisite': 3},
        {'name': 'Arreglos Bidimensionales', 'minimum_approved': 60, 'prerequisite': 4},
        {'name': 'Estructuras', 'minimum_approved': 75, 'prerequisite': 5},
        {'name': 'Apuntadores', 'minimum_approved': 90, 'prerequisite': 6},
        {'name': 'Clases', 'minimum_approved': 115, 'prerequisite': 7},
        {'name': 'Metodos', 'minimum_approved': 130, 'prerequisite': 8},
    ])

    op.bulk_insert(types, [
        {'name': 'Correcta'},
        {'name': 'Incorrecta'},
    ])

    op.bulk_insert(nodes, [
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'None', 'parent_node': 0},### cpp1
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 15', 'parent_node': 1},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'15\'', 'parent_node': 1},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'Error', 'parent_node': 1},

        ### cpp2
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 15', 'parent_node': 2},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'50\'', 'parent_node': 2},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 50', 'parent_node': 2},

        ### cpp3
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 12', 'parent_node': 3},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'12\'', 'parent_node': 3},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 7', 'parent_node': 3},

        ### cpp4
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 10', 'parent_node': 4},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'Error', 'parent_node': 4},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'a\'', 'parent_node': 4},

        ### cpp5
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'True\'', 'parent_node': 5},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 5', 'parent_node': 5},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = -5', 'parent_node': 5},

        ### cpp6
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = \'Error\'', 'parent_node': 6},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 0', 'parent_node': 6},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'0\'', 'parent_node': 6},

        ### cpp7
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'Error\'', 'parent_node': 7},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 150', 'parent_node': 7},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 60', 'parent_node': 7},

        ### cpp8
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 10', 'parent_node': 8},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 100', 'parent_node': 8},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = \'10\'', 'parent_node': 8},

        ### los nodos 9, 10, 12 y 13 ya dan -10 por ende game over, para no perder el hilo le puse el num 11 al que sigue

        ### cpp11
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 55', 'parent_node': 11},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 5', 'parent_node': 11},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 100', 'parent_node': 11},

        ### cpp15
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 4', 'parent_node': 15},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = -5', 'parent_node': 15},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 1', 'parent_node': 15},

        ### cpp17
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 5', 'parent_node': 17},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 2', 'parent_node': 17},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 15', 'parent_node': 17},

        ### cpp24
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 20', 'parent_node': 24},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 1', 'parent_node': 24},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 30', 'parent_node': 24},

        ### cpp27
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 200', 'parent_node': 27},
        {'subject_id': 1, 'type_id': 1, 'score': 10, 'answer_parent': 'c = 12', 'parent_node': 27},
        {'subject_id': 1, 'type_id': 2, 'score': -5, 'answer_parent': 'c = 3', 'parent_node': 27},

        ## la repesca es para que saquen 15 sino se jodieron

    ])


    "op.bulk_insert()"
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_subjects_approved')
    op.drop_table('nodes')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('subjects')
    # ### end Alembic commands ###
